name: AspergesCore
version: '${project.version}'
main: core.luuh.aspergescore.AspergesCore
api-version: 1.19
depend:
  - VerionCore
  - PlaceholderAPI
  - MythicMobs
  - SlimeWorldManager
commands:
  aspergescore:
    description: Manages core reloads.
    aliases:
      - ac
      - aspergesc
      - acore
  loadsb:
    description: Loads scoreboard to a specific player.
    aliases:
      - lsb
      - asb
      - sb
  itemlore:
    description: Manages item's name, lore and nbt.
    aliases:
      - ilore
      - iteml
      - il
      - item
  rename:
    description: Renames item.
  lore:
    description: Manages item's lore.
  health:
    description: Manages player's health.
  secretcommands:
    description: Manages secret commands.
  economy:
    description: Manages economy of players.
  is:
    description: Manages player's island.